steps:
  # 1. Construir a imagem Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/sga-h-api:$COMMIT_SHA', '.']

  # 2. Enviar a imagem para o Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/sga-h-api:$COMMIT_SHA']

  # 3. Fazer o Deploy da imagem compilada no Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'sga-h-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/sga-h-api:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      # OBS: Não precisamos repassar DATABASE_URL, --memory ou --allow-unauthenticated aqui, 
      # pois o Cloud Run preservará as configurações do serviço previamente criado.

images:
  - 'gcr.io/$PROJECT_ID/sga-h-api:$COMMIT_SHA'
